# Generated by Django 3.2.1 on 2021-05-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.IntegerField(choices=[(1, 'Седан'), (1, 'Хэчбек'), (1, 'Универсал'), (1, 'Купе')], verbose_name='Тип машины'),
        ),
    ]
