# Generated by Django 3.1.3 on 2020-12-11 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20201210_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.cart', verbose_name='Cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('our_stores', 'from our stores '), ('courier_np', 'by courier of NP to your address'), ('self_new_post', 'by New Post Office'), ('self_new_ukr_post', 'by UkrPost Office')], default='our_stores', max_length=100, verbose_name='Order status'),
        ),
    ]
